
spring:
  datasource:
    url:  jdbc:h2:mem:testDB
    driverClassName: org.h2.Driver
    username: labormaster
    password: hailsatandavetucker
    data:
    - ingredients-data.sql 
  jpa:
    generate-ddl: true