server:
  port: 8090
spring:
  data:    rest:
      base-path: /api

  h2:
    console:      enabled: true
  datasource:
    url:  jdbc:h2:mem:testDB;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: labormaster
    password: hailsatandavetuckerhttpL
  jpa:
    generate-ddl: true
    show-sql: true
JDA:
  token: "NzkxMTIxNzM3MDc2OTY1Mzk5.X-KjiA.qTfeGQYYdaWFUVXZULtMYX5vtrQ"
  testing-channel: 791402010943553586